"""Second commit

Revision ID: d1346da2ef3d
Revises: 3394ccf255d2
Create Date: 2021-11-17 18:32:17.981470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1346da2ef3d'
down_revision = '3394ccf255d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
